accent = "#ceabad"
cursor = "#6488EA"
foreground = "#E0F7FA"
background = "#0A1429"
selection_foreground = "#374cb3"
selection_background = "#d7ebe9"

color0 = "#0A1429"
color1 = "#e95c4b"
color2 = "#6488EA"
color3 = "#d7ebe9"
color4 = "#ceabad"
color5 = "#77aaa2"
color6 = "#d8d0b7"
color7 = "#e3e9f3"
color8 = "#51688E"
color9 = "#ed7b6d"
color10 = "#819fee"
color11 = "#dfefed"
color12 = "#f3ced0"
color13 = "#98cdc5"
color14 = "#fef5db"
color15 = "#f6f9ff"
